import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";
import "./globals.css";
import { SettingsProvider } from "./providers/SettingsProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// إضافة خط Cairo
const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin", "arabic"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} antialiased`}
      >
        <SettingsProvider>
          {children}
        </SettingsProvider>

        {/* Firebase config injected from user-provided credentials */}
        <Script id="firebase-config" strategy="beforeInteractive">
          {`
            window.__FIREBASE_CONFIG__ = {
              apiKey: "AIzaSyBwyEDuSNRfRnXVg_BXA9sKcvN7Lw1pd7s",
              authDomain: "test-4d0d3.firebaseapp.com",
              projectId: "test-4d0d3",
              appId: "1:908899179213:web:57628b96a72845e7162784",
              storageBucket: "test-4d0d3.firebasestorage.app"
            };
          `}
        </Script>
        {/* Load Firebase App + Firestore via CDN and expose minimal API on window.__FB */}
        <Script id="firebase-sdk-loader" type="module" strategy="beforeInteractive">
          {`
            import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
            import { getFirestore, doc, onSnapshot, setDoc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
            window.__FB = { initializeApp, getApps, getFirestore, doc, onSnapshot, setDoc };
          `}
        </Script>
      </body>
    </html>
  );
}